### PR TITLE
fix(oss): auto-detect embedding dimension to fix Qdrant mismatch with non-OpenAI embedders

### LINKED ISSUE #4212: Qdrant collection created with wrong dimensions when using Ollama embedder (nomic-embed-text)
## Bug

When using the OpenClaw plugin (or OSS mode generally) with Ollama's `nomic-embed-text` embedder, the Qdrant collection is created with **1536 dimensions** (OpenAI default), but `nomic-embed-text` produces **768-dimensional** vectors. This causes every `add()` and `search()` call to fail with a cryptic `Bad Request` error from Qdrant (dimension mismatch).

## Root Cause

In the Qdrant vector store class (`src/oss/src/vector_stores/qdrant.ts`):

```typescript
this.dimension = config.dimension || 1536;
```

The fallback is hardcoded to 1536 (OpenAI's `text-embedding-3-small`). When using any non-OpenAI embedder, the collection is created with the wrong vector size.

## Reproduction

1. Configure mem0 OSS with Ollama + nomic-embed-text:
```json
{
  "embedder": { "provider": "ollama", "config": { "model": "nomic-embed-text" } },
  "vectorStore": { "provider": "qdrant", "config": { "host": "localhost", "port": 6333 } }
}
```
2. Call `memory.add()` or `memory.search()`
3. Both fail with `Bad Request` — Qdrant rejects 768-dim vectors into a 1536-dim collection

## Workaround

Explicitly set `dimension: 768` in the vectorStore config:
```json
"vectorStore": {
  "provider": "qdrant",
  "config": { "host": "localhost", "port": 6333, "dimension": 768 }
}
```

## Suggested Fix

Auto-detect the embedding dimension from the configured embedder at init time (e.g., run a test embedding and read the vector length), rather than defaulting to 1536. This would make any embedder work out of the box without requiring users to know and manually set the dimension.

Alternatively, at minimum, log a warning or throw a clear error when the embedder's output dimension doesn't match the configured/default collection dimension.

## Environment

- mem0ai (JS/npm) v0.1.2
- Qdrant v1.13.0 (Docker)
- Ollama nomic-embed-text (768 dims)
- OpenClaw plugin `@mem0/openclaw-mem0`

### PR DESCRIPTION
**Pull request by utkarsh240799**
## Problem

Users using non-OpenAI embedding providers (Ollama/nomic-embed-text, Google/Gemini, HuggingFace, etc.) hit `Bad Request` errors when using Qdrant because the vector store was always created with a hardcoded default dimension of 1536 (OpenAI's dimension), regardless of the actual embedding model's output dimension.

This caused three related issues:
- **#4212** — Ollama + nomic-embed-text (768 dims) → Qdrant collection created with 1536 dims → `Bad Request` on insert
- **#4173** — Same root cause with different embedding providers
- **#4056** — Race condition during Qdrant collection creation + `memory_migrations` collection using wrong dimension

### 1. Probe-based dimension auto-detection
When no explicit dimension is provided, the `Memory` class now embeds a short probe string (`"dimension probe"`) at initialization time and reads the resulting vector length to determine the correct dimension. This happens **before** the vector store is created.

**Dimension resolution order:**
1. Explicit `vectorStore.config.dimension` (user override)
2. `embedder.config.embeddingDims` (embedder config)  
3. Auto-detected via probe embedding (new fallback)

### 2. Deferred vector store creation
The vector store is no longer created in the `Memory` constructor. Instead, it's created in an async `_autoInitialize()` method **after** the dimension is known. All public Memory methods (`add`, `search`, `getAll`, etc.) await initialization before proceeding via a lazy init gate (`_ensureInitialized()`).

### 3. Atomic Qdrant collection creation
Replaced the check-then-create pattern (TOCTOU race) with create-and-catch-409:
```typescript
try {
  await this.client.createCollection(name, { vectors: { size, distance: "Cosine" } });
} catch (error) {
  if (error?.status === 409) {
    // Collection already exists — verify dimension matches
  } else {
    throw error;
  }
}
```

### 4. Idempotent init guards for all vector stores
Every vector store with async initialization (Qdrant, Redis, Supabase, AzureAISearch, Vectorize) now uses a `_initPromise` singleton guard. This prevents double-initialization when `Memory` explicitly calls `await vectorStore.initialize()` after the constructor already fired it:

```typescript
private _initPromise?: Promise<void>;

async initialize(): Promise<void> {
  if (!this._initPromise) {
    this._initPromise = this._doInitialize();
  }
  return this._initPromise;
}
```

Without this guard:
- **Redis**: Double `connect()` → `"Socket already opened"`, plus `dropIndex`/`createIndex` destroys the index the first call just built
- **Qdrant**: Double `createCollection` → `409 Conflict` crash
- **Vectorize**: Double `indexes.create()` → Cloudflare API error
- **Supabase/AzureAISearch**: Redundant network calls and potential transient failures

### 5. Google embedder fix
Fixed hardcoded `outputDimensionality: 768` in `google.ts` — now uses `this.embeddingDims` from config.

## Files Changed

| File | Change |
|---|---|
| `src/oss/src/memory/index.ts` | Deferred vector store creation, lazy init gate, probe-based dimension detection |
| `src/oss/src/config/manager.ts` | Dimension resolution: explicit > embeddingDims > undefined (triggers probe) |
| `src/oss/src/vector_stores/qdrant.ts` | Atomic create-and-catch-409, idempotent init, transient error resilience |
| `src/oss/src/vector_stores/redis.ts` | Idempotent init guard |
| `src/oss/src/vector_stores/supabase.ts` | Idempotent init guard |
| `src/oss/src/vector_stores/azure_ai_search.ts` | Idempotent init guard |
| `src/oss/src/vector_stores/vectorize.ts` | Idempotent init guard |
| `src/oss/src/embeddings/google.ts` | Use `embeddingDims` config instead of hardcoded 768 |

### Unit Tests (61 tests)
- **`dimension-autodetect.test.ts`** (22 tests) — ConfigManager dimension resolution, MemoryVectorStore backward compat, Memory auto-initialization, error propagation
- **`config-manager.test.ts`** (5 tests) — ConfigManager dimension priority chain
- **`vector-stores-compat.test.ts`** (34 tests) — Backward compatibility for all 7 vector store implementations (MemoryVectorStore, Qdrant, Redis, Supabase, AzureAISearch, Vectorize, Langchain) with mocked clients

### End-to-End Tests (21 tests, against real instances)
- **`qdrant-e2e.test.ts`** (8 tests) — Against real Qdrant v1.13.0:
  - Reproduces the exact Bad Request error from #4212/#4173
  - Verifies 768-dim CRUD works after fix
  - Memory auto-detects dims via probe (full integration)
  - Explicit dimension and embeddingDims skip probe (backward compat)
  - Concurrent `ensureCollection` race condition (5 parallel instances)
  - `getUserId`/`setUserId` after concurrent init
  - `memory_migrations` uses dim=1 independently of main collection
- **`redis-e2e.test.ts`** (13 tests) — Against real Redis Stack:
  - Idempotent init (multiple concurrent calls)
  - Full CRUD: insert, search, get, update, delete
  - List with filters
  - `getUserId`/`setUserId` roundtrip
  - Correct dimension propagation from config

## Checklist

- [x] Fixes #4212, #4173, #4056
- [x] Backward compatible — explicit `dimension` config still works, no probe triggered
- [x] All existing tests pass
- [x] New unit tests for dimension resolution and backward compatibility
- [x] End-to-end tests against real Qdrant and Redis Stack instances
- [x] No breaking changes to public API
- [x] All vector store implementations verified (Qdrant, Redis, Supabase, AzureAISearch, Vectorize, Langchain, MemoryVectorStore)
- [x] Race conditions handled (concurrent init, TOCTOU collection creation)
- [x] Error messages are helpful (probe failure tells user to set dimension explicitly)

### CODE REVIEW

**Comment by whysosaket** [comment]
Once init fails, the Memory instance is permanently dead... no retry, no recovery. If the embedder was briefly down at startup, user has to recreate everything.

File: mem0-ts/src/oss/src/vector_stores/qdrant.ts [hunk 1]
```diff
@@ -286,66 +273,58 @@ export class Qdrant implements VectorStore {
     }
   }
 
-  async initialize(): Promise<void> {
+  private async ensureCollection(
```
Comment (whysosaket) [inline mem0-ts/src/oss/src/vector_stores/qdrant.ts:276]: ensureCollection silently swallows all non-dimension errors after a 409 — auth failures, network issues, etc. would be invisible.

**Comment by whysosaket** [comment]
E2E tests hard-fail without local Qdrant/Redis and have no skip mechanism.

**Review by whysosaket — DISMISSED** [review]
