### PR TITLE
fix(oss): OllamaLLM now respects configured url instead of always falling back to localhost

### LINKED ISSUE #4059: OllamaLLM constructor uses wrong config nesting — falls back to localhost:11434 ignoring configured URL
### 🐛 Describe the bug

When using the OSS SDK with Ollama as the LLM provider and a **remote** Ollama server (not localhost), the `OllamaLLM` class connects to `localhost:11434` instead of the configured URL. The embedder (`OllamaEmbedder`) works correctly — only the LLM is affected.

**Root cause:** Two issues in the config path:

**1. `OllamaLLM` constructor reads `config.config.url` (double-nested), but `LLMFactory.create()` passes the inner config object directly:**

```typescript
// LLMFactory.create() passes this.config.llm.config (flat object)
// e.g. { model: "llama3.2:3b", url: "http://remote-host:11434", baseURL: "http://remote-host:11434" }

// But OllamaLLM reads config.config.url (double-nested — undefined!)
class OllamaLLM {
  constructor(config) {
    this.ollama = new Ollama({
      host: config.config?.url || "http://localhost:11434"  // falls back to localhost
    });
  }
}
```

Compare with `OllamaEmbedder` which correctly reads `config.url`:
```typescript
class OllamaEmbedder {
  constructor(config) {
    this.ollama = new Ollama({
      host: config.url || "http://localhost:11434"  // works correctly
    });
  }
}
```

**2. `ConfigManager.mergeConfig()` strips `url` from the LLM config — only preserves `baseURL`:**

```typescript
// In mergeConfig, embedder config preserves url:
url: userConf?.url,  // preserved

// But LLM config does NOT include url in the return:
return {
  baseURL: userConf?.baseURL || defaultConf.baseURL,
  apiKey: ...,
  model: ...,
  modelProperties: ...
  // url is missing!
};
```

### Minimal Reproduction

```javascript
import { Memory } from "mem0ai/oss";

const memory = new Memory({
  version: "v1.1",
  embedder: {
    provider: "ollama",
    config: {
      model: "nomic-embed-text:latest",
      url: "http://10.0.0.100:11434",  // remote server
    },
  },
  llm: {
    provider: "ollama",
    config: {
      model: "llama3.2:3b",
      url: "http://10.0.0.100:11434",  // remote server — ignored!
    },
  },
  vectorStore: {
    provider: "qdrant",
    config: { url: "http://localhost:6333", collectionName: "test" },
  },
});

// Embedder connects to 10.0.0.100:11434 (correct)
// LLM connects to 127.0.0.1:11434 (wrong) -> ECONNREFUSED if no local Ollama
await memory.add([{ role: "user", content: "test" }], { userId: "test" });
// TypeError: fetch failed (cause: ECONNREFUSED 127.0.0.1:11434)
```

### Suggested Fix

**In `OllamaLLM` constructor** (`src/oss/src/llms/ollama.ts`):
```typescript
// Before:
this.ollama = new Ollama({ host: config.config?.url || "http://localhost:11434" });

// After:
this.ollama = new Ollama({ host: config.url || config.baseURL || config.config?.url || "http://localhost:11434" });
```

**In `ConfigManager.mergeConfig()`** (`src/oss/src/config/manager.ts`), add `url` to the LLM config return:
```typescript
return {
  baseURL: userConf?.baseURL || userConf?.url || defaultConf.baseURL,
  url: userConf?.url,  // add this
  apiKey: ...,
  model: ...,
};
```

### Environment
- mem0ai: 2.2.2
- - Node.js: 22
- - - ollama (npm): latest

### LINKED ISSUE #4104: How to configure openclaw-mem0 with Local Ollama when its installed on a different system in the network?
### Issue with current documentation:

The current documentation shows how to configure Local Models as follows: 
`
{
    "openclaw-mem0": {
        "enabled": true,
        "config": {
            "mode": "open-source",
            "userId": "your-user-id",
            "oss": {
                "embedder": {
          "provider": "ollama",
          "config": {
            "model": "nomic-embed-text"
          }
        },
                "vectorStore": {
          "provider": "qdrant",
          "config": {
            "host": "localhost",
            "port": 6333
          }
        },
                "llm": {
          "provider": "anthropic",
          "config": {
            "model": "claude-sonnet-4-20250514"
          }
        }      
      }    
    }  
  }
}
`

How do I configure LLM and Embedder if they are hosted on another system in the same network?

I tried the following: 

`
"openclaw-mem0": {
        "enabled": true,
        "config": {
          "mode": "open-source",
          "userId": "ubuntuuser",
          "oss": {
            "llm": {
              "provider": "ollama",
              "config": { "model": "qwen3:8b", "url": "http://192.168.56.1:11434" }
            },
            "embedder": {
              "provider": "ollama",
              "config": { "model": "nomic-embed-text", "url": "http://192.168.56.1:11434" }
            }
          }
        }
      }
`

But I am seeing when trying to check mem0

`
[ERROR] Error ensuring model exists: TypeError: fetch failed
[ERROR] Error ensuring model exists: TypeError: fetch failed
Telemetry event capture failed: TypeError: fetch failed
    at node:internal/deps/undici/undici:14902:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async UnifiedTelemetry.captureEvent (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4454:24)
    at async captureClientEvent (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4486:3)
    at async _Memory._initializeTelemetry (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4536:7) {
  [cause]: AggregateError [ETIMEDOUT]: 
      at internalConnectMultiple (node:net:1134:18)
      at afterConnectMultiple (node:net:1715:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error]
    ]
  }
}
Telemetry event capture failed: TypeError: fetch failed
    at node:internal/deps/undici/undici:14902:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async UnifiedTelemetry.captureEvent (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4454:24)
    at async captureClientEvent (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4486:3)
    at async _Memory._captureEvent (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4559:7)
    at async _Memory.getAll (file:///home/ubuntuuser/.openclaw/extensions/openclaw-mem0/node_modules/mem0ai/dist/oss/index.mjs:4921:5)
    at async OSSProvider.getAll (/home/ubuntuuser/.openclaw/extensions/openclaw-mem0/index.ts:288:21)
    at async Command.<anonymous> (/home/ubuntuuser/.openclaw/extensions/openclaw-mem0/index.ts:1209:30)
    at async Command.parseAsync (/home/ubuntuuser/.npm-global/lib/node_modules/openclaw/node_modules/commander/lib/command.js:1122:5)
    at async runCli (file:///home/ubuntuuser/.npm-global/lib/node_modules/openclaw/dist/run-main-ymxgIjRa.js:407:2) {
  [cause]: AggregateError [ETIMEDOUT]: 
      at internalConnectMultiple (node:net:1134:18)
      at afterConnectMultiple (node:net:1715:7) {
    code: 'ETIMEDOUT',
    [errors]: [
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error], [Error], [Error],
      [Error]
    ]
  }
}
Mode: open-source
User: ubuntuuser
Total memories: 0
Graph enabled: false

`

### PR DESCRIPTION
**Pull request by kartik-mem0**
## Description                                                                                                                                                                                     
   
  `OllamaLLM` in the TypeScript SDK ignored the user-provided `url` config and always connected to `localhost:11434`, even when a remote Ollama server was configured.                               
                                                            
  **Root cause:** The constructor used `config.config?.url` (double-nested, always `undefined`) instead of `config.url`. Additionally, the `url` field was missing from the LLM config pipeline —
  ConfigManager didn't pass it through, and Zod validation stripped it.

  **Fix:** Three changes to match how the embedder side already works correctly:
  - `ollama.ts` — Fix `config.config?.url` → `config.url || config.baseURL`
  - `config/manager.ts` — Pass `url` through in LLM config
  - `types/index.ts` — Add `url` to `LLMConfig` interface and Zod schema

  Fixes #4059, fixes #4104

  ## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

  ## How Has This Been Tested?

  - [x] Unit Test

  4 new tests in `config-manager.test.ts` covering:
  - URL preserved in LLM config when provided
  - `baseURL` and `url` coexist without interference
  - Default `baseURL` fallback when neither is provided
  - Both embedder and LLM `url` preserved independently

  ## Checklist:

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] New and existing unit tests pass locally with my changes

  ## Maintainer Checklist

  - [x] closes #4059
  - [x] closes #4104

### CODE REVIEW

File: mem0-ts/src/oss/src/llms/ollama.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export class OllamaLLM implements LLM {
 
   constructor(config: LLMConfig) {
     this.ollama = new Ollama({
-      host: config.config?.url || "http://localhost:11434",
+      host: config.url || config.baseURL || "http://localhost:11434",
```
Comment (utkarsh240799) [inline mem0-ts/src/oss/src/llms/ollama.ts:14]: Add this change in the constructor of OllamaEmbedder class (oss/src/embeddings/ollama.ts) as well.

Comment (kartik-mem0) [reply mem0-ts/src/oss/src/llms/ollama.ts:14]: comment resolved.
